### ISSUE TITLE
[FEAT] 작성하기 API

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRoServer_dev#28]
## 📌  Feature Issue

- 작성하기 API 를 개발합니다!
- 서버로 오는 데이터들은 완벽히 정제되어 내려온다고 가정합니다! (클라 단에서 에러 핸들링)
## 📝  To-do

- [x] 비즈니스 로직 분리
- [x] DTO 정의 (preview, detail이 합쳐져야함)
- [x] API 개발
- [x] 테스트
- [ ] 클라 - 서버 연동 테스트(사진 저장 확인)
