### ISSUE TITLE
[FIX] 경유지 2개 -> 1개 조정 작업 반영

### ISSUE THREAD

**Issue by yaeoni** [TeamChaRo/ChaRoServer_dev#49]
## 📌  FIX Issue

* 기존 경유지가 2개에서 1개로 바뀜에 따라 DB 구조와 Detail 테이블, 상세보기 조회 API수정
* 디비속 경유지 2개인 것들은 삭제
## 📝  To-do

- [x] DB wayTwo 관련 삭제  / wayOne -> way 로 정정
- [x] 모델 정정
- [x] 상세보기 API 정정
- [x] 작성하기 API 정정
